version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u noxaro -p ${docker_password}
      - run: docker build --pull -t "noxaro/cmake-jdk" .
      - run: docker push "noxaro/cmake-jdk:latest"